name: CI
on:
  push:
    branches:
      - main
      - master
      - test
  pull_request:
    branches:
      - main
      - master
      - test
jobs:
  build:
    runs-on: windows-latest
    steps:
      # check out code
      - name: check out the code
        uses: actions/checkout@v4
      # set up our environment
      - name: set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      # Run tests
      - name: Run tests
        run: mvn -B test
      #Build application
      - name: Run application
        run: mvn -B package -DskipTests
        env:
          password: abeded